KermesseElysium/Models/Rol.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseElysium.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Rol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rol()
        {
            this.RolOpcion = new HashSet<RolOpcion>();
            this.RolUsuario = new HashSet<RolUsuario>();
        }

        [Display(Name = "ID Rol")]
        public int idRol { get; set; }

        [Display(Name = "Descripción Rol")]
        [DataType(DataType.Text, ErrorMessage = "Por favor ingrese un dato de tipo texto")]
        [Required(ErrorMessage = "Este campo es requerido")]
        [StringLength(100, ErrorMessage = "Longitud máxima 100")]
        public string rolDescripcion { get; set; }

        [Display(Name = "Estado")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public int estado { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolOpcion> RolOpcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolUsuario> RolUsuario { get; set; }
    }
}

KermesseElysium/Controllers/RolsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KermesseElysium.Models;
using Microsoft.Reporting.WebForms;

namespace KermesseElysium.Controllers
{
    public class RolsController : Controller
    {
        private DBKermesseElysiumEntities db = new DBKermesseElysiumEntities();

        // GET: Rols
        public ActionResult Index(string buscar = "")
        {
            var rol = from ro in db.Rol select ro;

            if (!string.IsNullOrEmpty(buscar))
            {
                rol = rol.Where(ro => ro.rolDescripcion.Contains(buscar));
            }
            return View(rol.ToList());
        }

        // GET: Rols/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rol rol = db.Rol.Find(id);
            if (rol == null)
            {
                return HttpNotFound();
            }
            return View(rol);
        }

        // GET: Rols/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Rols/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idRol,rolDescripcion,estado")] Rol rol)
        {
            if (ModelState.IsValid)
            {
                rol.estado = 1;
                db.Rol.Add(rol);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(rol);
        }

        // GET: Rols/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rol rol = db.Rol.Find(id);
            if (rol == null)
            {
                return HttpNotFound();
            }
            return View(rol);
        }

        // POST: Rols/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idRol,rolDescripcion,estado")] Rol rol)
        {
            if (ModelState.IsValid)
            {
                rol.estado = 2;
                db.Entry(rol).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(rol);
        }

        // GET: Rols/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rol rol = db.Rol.Find(id);
            if (rol == null)
            {
                return HttpNotFound();
            }
            return View(rol);
        }

        // POST: Rols/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Rol rol = db.Rol.Find(id);
            rol.estado = 3;
            if (rol.estado.Equals(1) || rol.estado.Equals(2))
            {
                rol.estado = 3;
            }
            else
            {
                rol.estado = 2;
            }
            db.Entry(rol).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult VerReporteRol(string tipo, string buscar = "")
        {
            LocalReport rpt = new LocalReport();
            string mt, enc, f;
            string[] s;
            Warning[] w;


            string ruta = Path.Combine(Server.MapPath("~/Reportes"), "RRol.rdlc");
            string deviceInfo = @"<DeviceInfo>
                      <MarginTop>0cm</MarginTop>
                      <MarginLeft>0cm</MarginLeft>
                      <MarginRight>0cm</MarginRight>
                      <MarginBottom>0cm</MarginBottom>
                        <EmbedFonts>None</EmbedFonts>
                    </DeviceInfo>";

            rpt.ReportPath = ruta;

            DBKermesseElysiumEntities modelo = new DBKermesseElysiumEntities();

            List<Rol> lista = new List<Rol>();
            var rol = from p in db.Rol select p;
            rol = rol.Where(tc => tc.estado == 1 || tc.estado == 2);
            if (!string.IsNullOrEmpty(buscar))
            {
                rol = rol.Where(tc => tc.rolDescripcion.Equals(buscar));
            }

            lista = rol.ToList();

            ReportDataSource rds = new ReportDataSource("DsRol", lista);
            rpt.DataSources.Add(rds);

            var b = rpt.Render(tipo, deviceInfo, out mt, out enc, out f, out s, out w);

            return File(b, mt);
        }

        public ActionResult VerReporteRolIndiv(int id)
        {
            LocalReport rpt = new LocalReport();
            string mt, enc, f;
            string[] s;
            Warning[] w;

            string ruta = Path.Combine(Server.MapPath("~/Reportes"), "RRolIndiv.rdlc");
            string deviceInfo = @"<DeviceInfo>
                      <MarginTop>0cm</MarginTop>
                      <MarginLeft>0cm</MarginLeft>
                      <MarginRight>0cm</MarginRight>
                      <MarginBottom>0cm</MarginBottom>
                        <EmbedFonts>None</EmbedFonts>
                    </DeviceInfo>";

            rpt.ReportPath = ruta;

            DBKermesseElysiumEntities modelo = new DBKermesseElysiumEntities();

            var rol = from p in db.Rol select p;
            rol = rol.Where(t => t.idRol == id);


            ReportDataSource rds = new ReportDataSource("DsRol", rol.ToList());
            rpt.DataSources.Add(rds);

            var b = rpt.Render("PDF", deviceInfo, out mt, out enc, out f, out s, out w);

            return File(b, mt);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KermesseElysium/Views/Rols/Create.cshtml
@model KermesseElysium.Models.Rol

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Rol</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li class="breadcrumb-item"> @Html.ActionLink("Rol", "Index", "Rols")</li>
                    <li class="breadcrumb-item active">Crear</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
        <div class="row mb-2">

        </div>
    </div><!-- /.container-fluid -->
</div>


<div class="card card-secondary">
    <div class="card-header">
        <h3 class="card-title">Añadir rol</h3>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="card-body">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.rolDescripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.rolDescripcion, new { htmlAttributes = new { @class = "form-control"} })
                        @Html.ValidationMessageFor(model => model.rolDescripcion, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="card-footer">
                    <input type="submit" value="Añadir" class="btn btn-secondary" />
                </div>
            </div>
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KermesseElysium/Views/Rols/Delete.cshtml
@model KermesseElysium.Models.Rol

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    string titulo = "eliminar";
    string boton = "Eliminar";
}
@if (Model.estado.Equals(3))
{
    titulo = "habilitar";
    boton = "Habilitar";
}


<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Rol</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li class="breadcrumb-item"> @Html.ActionLink("Detalle de tasa", "Index", "TasaCambioDets")</li>
                    <li class="breadcrumb-item active">@boton</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
        <div class="row mb-2">

        </div>
    </div><!-- /.container-fluid -->
</div>

<div class="card card-secondary">
    <div class="card-header">
        <h3 class="card-title">¿Estás seguro que deseas @titulo este rol?</h3>
    </div>
    <div class="card-body">
        <div class="info-box bg-light">
            <div class="info-box-content">
                @Html.LabelFor(model => model.rolDescripcion, htmlAttributes: new { @class = "info-box-number mb-0" })
                <span class="info-box-text">@Html.DisplayFor(model => model.rolDescripcion)</span>
            </div>
        </div>
    </div>
    <div class="card-footer">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="@boton" class="btn btn-secondary" />
                <a class="btn btn-default" href="@Url.Action("Index", "Rols")">Volver</a>
            </div>
        }
    </div>
</div>

KermesseElysium/Views/Rols/Details.cshtml
@model KermesseElysium.Models.Rol

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Rol</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li class="breadcrumb-item"> @Html.ActionLink("Rol", "Index", "Rols")</li>
                    <li class="breadcrumb-item active">Detalles</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
        <div class="row mb-2">

        </div>
    </div><!-- /.container-fluid -->
</div>


<div class="card card-secondary">
    <div class="card-header">
        <h3 class="card-title">Detalles del rol</h3>
    </div>
    <div class="card-body">
        <div class="info-box bg-light">
            <div class="info-box-content">
                @Html.LabelFor(model => model.rolDescripcion, htmlAttributes: new { @class = "info-box-number mb-0" })
                <span class="info-box-text">@Html.DisplayFor(model => model.rolDescripcion)</span>
            </div>
        </div>
    </div>
    <div class="card-footer">
        <a class="btn btn-default" href="@Url.Action("Index", "Rols")">Volver</a>
    </div>
</div>

KermesseElysium/Views/Rols/Edit.cshtml
@model KermesseElysium.Models.Rol

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Rol</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li class="breadcrumb-item"> @Html.ActionLink("Rol", "Index", "Rols")</li>
                    <li class="breadcrumb-item active">Editar</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
        <div class="row mb-2">

        </div>
    </div><!-- /.container-fluid -->
</div>


<div class="card card-secondary">
    <div class="card-header">
        <h3 class="card-title">Editar rol</h3>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="card-body">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.idRol)

                <div class="form-group">
                    @Html.LabelFor(model => model.rolDescripcion, "tasaCambio", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.rolDescripcion, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.rolDescripcion, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Actualizar" class="btn btn-secondary" />
                    </div>
                </div>
            </div>
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KermesseElysium/Views/Rols/Index.cshtml
@model IEnumerable<KermesseElysium.Models.Rol>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Rol</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li class="breadcrumb-item active">Rol</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
        <div class="row mb-2">

        </div>
    </div><!-- /.container-fluid -->
</div>

<div class="card">
    <div class="card-header">
        <div style="text-align:right;">
            <button type="button" class="btn btn-secondary btn-sm" onclick="location.href='@Url.Action("Create", "Rols")'">
                <i class="fas fa-plus"></i> Añadir rol
            </button>
            <div class="btn-group">
                <button type="button" class="btn-sm btn-secondary dropdown-toggle dropdown-icon border border-secondary" data-toggle="dropdown">
                    Exportar
                </button>
                <div class="dropdown-menu" role="menu">
                    <a class="dropdown-item" href="@Url.Action("VerReporteRol", new { tipo = "PDF", buscar = Request.Form["buscar"] })">PDF</a>
                    <a class="dropdown-item" href="@Url.Action("VerReporteRol", new { tipo = "Word", buscar = Request.Form["buscar"] })">Word</a>
                    <a class="dropdown-item" href="@Url.Action("VerReporteRol", new { tipo = "Excel", buscar = Request.Form["buscar"] })">Excel</a>
                </div>
            </div>
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        @using (Html.BeginForm("Index", "TasaCambioDets", FormMethod.Post))
        {
            <div style="text-align:right; float:right;">
                <div class"row">
                    <div class="input-group">
                        @Html.TextBox("buscar", "", new { @class = "form-control" })
                        <button type="submit" class="btn btn-dark">Buscar</button>
                    </div>
                </div>
            </div>
        }
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.rolDescripcion)</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    string estado = "table-default";
                    string imgEstado = "fa-ban";
                    string titleEstado = "Eliminar";
                    if (item.estado.Equals(3))
                    {
                        estado = "table-danger";
                        imgEstado = "fa-check";
                        titleEstado = "Habilitar";
                    }
                    <tr class="@estado">
                        <td>
                            @Html.DisplayFor(modelItem => item.rolDescripcion)
                        </td>
                        <td>
                            <span style="cursor:pointer;" title="Ver detalles"><a href="@Url.Action("Details", "Rols", new { id = item.idRol })" style="color:black;"><i class="fas fa-eye"></i></a></span>
                            @if (!item.estado.Equals(3))
                            {
                                <span style="cursor:pointer;" title="Editar"><a href="@Url.Action("Edit", "Rols", new { id = item.idRol })" style="color:black;"><i class="fas fa-edit"></i></a></span>
                                <span style="cursor:pointer;" title="Exportar a PDF"><a href="@Url.Action("VerReporteRolIndiv", "Rols", new { id = item.idRol })" style="color:black;"><i class="fas fa-file-export"></i></a></span>

                            }
                            <span style="cursor:pointer;" title="@titleEstado"><a href="@Url.Action("Delete", "Rols", new { id = item.idRol })" style="color:black;"><i class="fas @imgEstado"></i></a></span>
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.rolDescripcion)</th>
                    <th>Acciones</th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>