KermesseElysium/Models/Denominacion.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseElysium.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Denominacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Denominacion()
        {
            this.ArqueoCajaDet = new HashSet<ArqueoCajaDet>();
        }

        [Display(Name = "ID Denominación")]
        public int idDenominacion { get; set; }

        [Display(Name = "Moneda")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public int moneda { get; set; }

        [Display(Name = "Valor")]
        [DataType(DataType.Currency, ErrorMessage = "Por favor ingrese un dato de tipo decimal")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public decimal valor { get; set; }

        [Display(Name = "Valor en Letras")]
        [DataType(DataType.Text, ErrorMessage = "Por favor ingrese un dato de tipo texto")]
        [Required(ErrorMessage = "Este campo es requerido")]
        [StringLength(100, ErrorMessage = "Longitud máxima 100")]
        public string valorLetras { get; set; }

        [Display(Name = "Estado")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public int estado { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArqueoCajaDet> ArqueoCajaDet { get; set; }
        public virtual Moneda Moneda1 { get; set; }
    }
}

KermesseElysium/Controllers/DenominacionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KermesseElysium.Models;
using Microsoft.Reporting.WebForms;

namespace KermesseElysium.Controllers
{
    public class DenominacionsController : Controller
    {
        private DBKermesseElysiumEntities db = new DBKermesseElysiumEntities();

        // GET: Denominacions
        public ActionResult Index(string buscar = "")

        {
            var denominacion = from g in db.Denominacion select g;

            if (!string.IsNullOrEmpty(buscar))
            {
                denominacion = denominacion.Where(g => g.valorLetras.Equals(buscar));
            }

            return View(denominacion.ToList());
        }

        // GET: Denominacions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Denominacion denominacion = db.Denominacion.Find(id);
            if (denominacion == null)
            {
                return HttpNotFound();
            }
            return View(denominacion);
        }

        // GET: Denominacions/Create
        public ActionResult Create()
        {
            ViewBag.moneda = new SelectList(db.Moneda.Where(d => d.estado == 1 || d.estado == 2), "idMoneda", "nombre");
            return View();
        }

        // POST: Denominacions/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idDenominacion,moneda,valor,valorLetras,estado")] Denominacion denominacion)
        {
            if (ModelState.IsValid)
            {
                denominacion.estado = 1;
                db.Denominacion.Add(denominacion);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.moneda = new SelectList(db.Moneda, "idMoneda", "nombre", denominacion.moneda);
            return View(denominacion);
        }

        // GET: Denominacions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Denominacion denominacion = db.Denominacion.Find(id);
            if (denominacion == null)
            {
                return HttpNotFound();
            }
            ViewBag.moneda = new SelectList(db.Moneda.Where(d => d.estado == 1 || d.estado == 2), "idMoneda", "nombre", denominacion.moneda);
            return View(denominacion);
        }

        // POST: Denominacions/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idDenominacion,moneda,valor,valorLetras,estado")] Denominacion denominacion)
        {
            if (ModelState.IsValid)
            {
                denominacion.estado = 2;
                db.Entry(denominacion).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.moneda = new SelectList(db.Moneda, "idMoneda", "nombre", denominacion.moneda);
            return View(denominacion);
        }

        // GET: Denominacions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Denominacion denominacion = db.Denominacion.Find(id);
            if (denominacion == null)
            {
                return HttpNotFound();
            }
            return View(denominacion);
        }

        // POST: Denominacions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Denominacion denominacion = db.Denominacion.Find(id);
            if (denominacion.estado.Equals(1) || denominacion.estado.Equals(2))
            {
                denominacion.estado = 3;
            }
            else
            {
                denominacion.estado = 2;
            }
            db.Entry(denominacion).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult ReporteDenominacions(string tipo, string buscar = "")
        {

            LocalReport rpt = new LocalReport();
            string mt, enc, f;
            string[] s;
            Warning[] w;

            string ruta = Path.Combine(Server.MapPath("~/Reportes"), "RDenominacion.rdlc");
            string deviceInfo = @"<DeviceInfo>
                      <MarginTop>0cm</MarginTop>
                      <MarginLeft>0cm</MarginLeft>
                      <MarginRight>0cm</MarginRight>
                      <MarginBottom>0cm</MarginBottom>
                        <EmbedFonts>None</EmbedFonts>
                    </DeviceInfo>";

            rpt.ReportPath = ruta;

            DBKermesseElysiumEntities modelo = new DBKermesseElysiumEntities();

            var Denominacion = from m in db.vw_denominacion select m;

            if (!string.IsNullOrEmpty(buscar))
            {
                Denominacion = Denominacion.Where(m => m.valorLetras.Contains(buscar));
            }

            List<vw_denominacion> ListaDen = new List<vw_denominacion>();
            ListaDen = Denominacion.ToList();

            ReportDataSource rds = new ReportDataSource("DSDenominacion", ListaDen);
            rpt.DataSources.Add(rds);

            var b = rpt.Render(tipo, deviceInfo, out mt, out enc, out f, out s, out w);

            return File(b, mt);
        }
        public ActionResult ReporteDenominacionIndiv(int id)
        {
            LocalReport rpt = new LocalReport();
            string mt, enc, f;
            string[] s;
            Warning[] w;

            string ruta = Path.Combine(Server.MapPath("~/Reportes"), "RDenominacionIndiv.rdlc");
            string deviceInfo = @"<DeviceInfo>
                      <MarginTop>0cm</MarginTop>
                      <MarginLeft>0cm</MarginLeft>
                      <MarginRight>0cm</MarginRight>
                      <MarginBottom>0cm</MarginBottom>
                        <EmbedFonts>None</EmbedFonts>
                    </DeviceInfo>";

            rpt.ReportPath = ruta;

            var Denominacion = from m in db.vw_denominacion select m;
            Denominacion = Denominacion.Where(m => m.idDenominacion == id);

            ReportDataSource rds = new ReportDataSource("DSDenominacion", Denominacion.ToList());
            rpt.DataSources.Add(rds);

            var b = rpt.Render("PDF", deviceInfo, out mt, out enc, out f, out s, out w);

            return File(b, mt);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KermesseElysium/Views/Denominacions/Create.cshtml
@model KermesseElysium.Models.Denominacion

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Denominacion</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li class="breadcrumb-item"> @Html.ActionLink("Denominacion", "Index", "Denominacions")</li>
                    <li class="breadcrumb-item active">Crear</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
        <div class="row mb-2">

        </div>
    </div><!-- /.container-fluid -->
</div>

<div class="card card-secondary">
    <div class="card-header">
        <h3 class="card-title">Registrar Denominacion</h3>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="card-body">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.moneda, "moneda", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("moneda", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.moneda, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.valor, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.valor, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.valor, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.valorLetras, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.valorLetras, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.valorLetras, "", new { @class = "text-danger" })
                    </div>
                </div>



            </div>
        </div>
        <div class="card-footer">
            <input type="submit" value="Crear" class="btn btn-secondary" />
        </div>
    }
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KermesseElysium/Views/Denominacions/Delete.cshtml
@model KermesseElysium.Models.Denominacion

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    string titulo = "eliminar";
    string boton = "Eliminar";
}
@if (Model.estado.Equals(3))
{
    titulo = "habilitar";
    boton = "Habilitar";
}
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Gastos</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li class="breadcrumb-item"> @Html.ActionLink("Denominacion", "Index", "Denominacions")</li>
                    <li class="breadcrumb-item active">@boton</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
        <div class="row mb-2">

        </div>
    </div><!-- /.container-fluid -->
</div>

<div class="card card-secondary">
    <div class="card-header">
        <h3 class="card-title">¿Estás seguro que deseas @titulo esta Denominacion?</h3>
    </div>
    <div class="card-body">


    </div>
    <div class="card-footer">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="info-box bg-light">
                <div class="info-box-content">

                    @Html.LabelFor(model => model.valor, htmlAttributes: new { @class = "info-box-number mb-0" })
                    <span class="info-box-text">@Html.DisplayFor(model => model.valor)</span>
                </div>
            </div>
            <div class="info-box bg-light">
                <div class="info-box-content">

                    @Html.LabelFor(model => model.valorLetras, htmlAttributes: new { @class = "info-box-number mb-0" })
                    <span class="info-box-text">@Html.DisplayFor(model => model.valorLetras)</span>
                </div>
            </div>
            <div class="info-box bg-light">
                <div class="info-box-content">
                    @Html.LabelFor(model => model.Moneda1.nombre, htmlAttributes: new { @class = "info-box-number mb-0" })
                    <span class="info-box-text">@Html.DisplayFor(model => model.Moneda1.nombre)</span>
                </div>
            </div>

            <div class="form-actions no-color">
                <input type="submit" value="@boton" class="btn btn-secondary" />
                <a class="btn btn-default" href="@Url.Action("Index", "Denominacions")">Volver</a>
            </div>
        }
    </div>
</div>

KermesseElysium/Views/Denominacions/Details.cshtml
@model KermesseElysium.Models.Denominacion

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Denominacion</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li class="breadcrumb-item"> @Html.ActionLink("Denominacion", "Index", "Denominacions")</li>
                    <li class="breadcrumb-item active">Detalles</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
        <div class="row mb-2">

        </div>
    </div><!-- /.container-fluid -->
</div>

<div class="card card-secondary">
    <div class="card-header">
        <h3 class="card-title">Detalles denominacion</h3>
    </div>
    <div class="card-body">

        <div class="info-box bg-light">
            <div class="info-box-content">

                @Html.LabelFor(model => model.valor, htmlAttributes: new { @class = "info-box-number mb-0" })
                <span class="info-box-text">@Html.DisplayFor(model => model.valor)</span>
            </div>
        </div>
        <div class="info-box bg-light">
            <div class="info-box-content">

                @Html.LabelFor(model => model.valorLetras, htmlAttributes: new { @class = "info-box-number mb-0" })
                <span class="info-box-text">@Html.DisplayFor(model => model.valorLetras)</span>
            </div>
        </div>
        <div class="info-box bg-light">
            <div class="info-box-content">
                @Html.LabelFor(model => model.Moneda1.nombre, htmlAttributes: new { @class = "info-box-number mb-0" })
                <span class="info-box-text">@Html.DisplayFor(model => model.Moneda1.nombre)</span>
            </div>
        </div>

        
    </div>
    <div class="card-footer">
        <a class="btn btn-default" href="@Url.Action("Index", "Denominacions")">Volver</a>
    </div>
</div>

KermesseElysium/Views/Denominacions/Edit.cshtml
@model KermesseElysium.Models.Denominacion
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Denominacion</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li class="breadcrumb-item"> @Html.ActionLink("Denominacion", "Index", "Denominacions")</li>
                    <li class="breadcrumb-item active">Editar</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
        <div class="row mb-2">

        </div>
    </div><!-- /.container-fluid -->
</div>

<div class="card card-secondary">
    <div class="card-header">
        <h3 class="card-title">Editar denominacion</h3>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

<div class="card-body">
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idDenominacion)

        <div class="form-group">
            @Html.LabelFor(model => model.moneda, "moneda", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("moneda", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.moneda, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.valorLetras, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.valorLetras, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.valorLetras, "", new { @class = "text-danger" })
            </div>
        </div>
 
        <div class="card-footer">
            <input type="submit" value="Actualizar" class="btn btn-secondary" />
        </div>
    </div>
</div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KermesseElysium/Views/Denominacions/Index.cshtml
@model IEnumerable<KermesseElysium.Models.Denominacion>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Denominación</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li class="breadcrumb-item active">Denominación</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

<div class="card">
    <div class="card-header">
        <div style="text-align:right;">
            <button type="button" class="btn btn-secondary btn-sm" onclick="location.href='@Url.Action("Create", "Denominacions")'">
                <i class="fas fa-plus"></i> Registrar denominación
            </button>
            <div class="btn-group">
                <button type="button" class="btn-sm btn-secondary dropdown-toggle dropdown-icon border border-secondary" data-toggle="dropdown">
                    Exportar
                </button>
                <div class="dropdown-menu" role="menu">
                    <a class="dropdown-item" target="_blank" href="@Url.Action("ReporteDenominacions", new { tipo = "PDF", buscar = Request.Form["buscar"] })">PDF</a>
                    <a class="dropdown-item" target="_blank" href="@Url.Action("ReporteDenominacions", new { tipo = "Word", buscar = Request.Form["buscar"] })">Word</a>
                    <a class="dropdown-item" target="_blank" href="@Url.Action("ReporteDenominacions", new { tipo = "Excel", buscar = Request.Form["buscar"] })">Excel</a>
                </div>
            </div>
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        @using (Html.BeginForm("Index", "Denominacions", FormMethod.Post))
        {
            <div style="text-align:right; float:right;">
                <div class"row">
                    <div class="input-group">
                        @Html.TextBox("buscar", "", new { @class = "form-control" })
                        <button type="submit" class="btn btn-dark">Buscar</button>
                    </div>
                </div>
            </div>
        }
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>

                    <th>
                        @Html.DisplayNameFor(model => model.valor)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.valorLetras)
                    </th>
                  
                    <th>
                        @Html.DisplayNameFor(model => model.Moneda1.nombre)
                    </th>


                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    string estado = "table-default";
                    string imgEstado = "fa-ban";
                    string titleEstado = "Eliminar";
                    if (item.estado.Equals(3))
                    {
                        estado = "table-danger";
                        imgEstado = "fa-check";
                        titleEstado = "Habilitar";
                    }
                    <tr class="@estado">
                        <td>
                            @Html.DisplayFor(modelItem => item.valor)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.valorLetras)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.Moneda1.nombre)
                        </td>

                        <td>
                            <span style="cursor:pointer;" title="Ver detalles"><a href="@Url.Action("Details", "Denominacions", new { id = item.idDenominacion })" style="color:black;"><i class="fas fa-eye"></i></a></span>
                            @if (!item.estado.Equals(3))
                            {
                                <span style="cursor:pointer;" title="Editar"><a href="@Url.Action("Edit", "Denominacions", new { id = item.idDenominacion })" style="color:black;"><i class="fas fa-edit"></i></a></span>
                                <span style="cursor:pointer;" title="Exportar a PDF"><a href="@Url.Action("ReporteDenominacionIndiv", "Denominacions", new { id = item.idDenominacion })" style="color:black;"><i class="fas fa-file-export"></i></a></span>
                            }
                            <span style="cursor:pointer;" title="@titleEstado"><a href="@Url.Action("Delete", "Denominacions", new { id = item.idDenominacion })" style="color:darkred;"><i class="fas @imgEstado"></i></a></span>
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.valor)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.valorLetras)
                    </th>
                    
                    <th>
                        @Html.DisplayNameFor(model => model.Moneda1.nombre)
                    </th>

                    <th>Acciones</th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>