KermesseElysium/Models/IngresoComunidadDet.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseElysium.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class IngresoComunidadDet
    {
        [Display(Name = "Id Ingreso Comunidad Det")]
        public int idIngresoComunidadDet { get; set; }

        [Display(Name = "Ingreso Comunidad")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public int ingresoComunidad { get; set; }

        [Display(Name = "Bono")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public int bono { get; set; }

        [Display(Name = "Denominación")]
        [DataType(DataType.Text, ErrorMessage = "Por favor ingrese un dato de tipo texto")]
        [Required(ErrorMessage = "Este campo es requerido")]
        [StringLength(100, ErrorMessage = "Longitud máxima 100")]
        public string denominacion { get; set; }

        [Display(Name = "Cantidad")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public int cantidad { get; set; }

        [Display(Name = "Subtotal Bono")]
        [DataType(DataType.Currency, ErrorMessage = "Por favor ingrese un dato de tipo decimal")]
        [Required(ErrorMessage = "Este campo es requerido")]
        public double subTotalBono { get; set; }

        public virtual ControlBono ControlBono { get; set; }
        public virtual IngresoComunidad IngresoComunidad1 { get; set; }
    }
}

KermesseElysium/Controllers/IngresoComunidadDetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KermesseElysium.Models;
using Microsoft.Reporting.WebForms;

namespace KermesseElysium.Controllers
{
    public class IngresoComunidadDetsController : Controller
    {
        private DBKermesseElysiumEntities db = new DBKermesseElysiumEntities();

        // GET: IngresoComunidadDets
        public ActionResult Index(string buscar = "")
        {
            var ingresoComunidadDet = from ic in db.vw_ingresocomunidaddet select ic;

            if (!string.IsNullOrEmpty(buscar))
            {
                ingresoComunidadDet = ingresoComunidadDet.Where(ic => ic.ingresoComunidad.Contains(buscar) || ic.bono.Contains(buscar) || ic.denominacion.Contains(buscar) || ic.bono.Contains(buscar));
            }

            return View(ingresoComunidadDet.ToList());
        }

        // GET: IngresoComunidadDets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            vw_ingresocomunidaddet ingresoComunidadDet = db.vw_ingresocomunidaddet.Find(id);
            if (ingresoComunidadDet == null)
            {
                return HttpNotFound();
            }
            return View(ingresoComunidadDet);
        }

        // GET: IngresoComunidadDets/Create
        public ActionResult Create()
        {
            ViewBag.bono = new SelectList(db.ControlBono.Where(ic => ic.estado == 1 || ic.estado == 2), "idBono", "nombre");
            ViewBag.ingresoComunidad = new SelectList(db.IngresoComunidad, "idIngresoComunidad", "idIngresoComunidad");
            return View();
        }

        // POST: IngresoComunidadDets/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idIngresoComunidadDet,ingresoComunidad,bono,denominacion,cantidad,subTotalBono")] IngresoComunidadDet ingresoComunidadDet)
        {
            if (ModelState.IsValid)
            {
                db.IngresoComunidadDet.Add(ingresoComunidadDet);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.bono = new SelectList(db.ControlBono.Where(ic => ic.estado == 1 || ic.estado == 2), "idBono", "nombre", ingresoComunidadDet.bono);
            ViewBag.ingresoComunidad = new SelectList(db.IngresoComunidad, "idIngresoComunidad", "idIngresoComunidad", ingresoComunidadDet.ingresoComunidad);
            return View(ingresoComunidadDet);
        }

        // GET: IngresoComunidadDets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IngresoComunidadDet ingresoComunidadDet = db.IngresoComunidadDet.Find(id);
            if (ingresoComunidadDet == null)
            {
                return HttpNotFound();
            }
            ViewBag.bono = new SelectList(db.ControlBono.Where(ic => ic.estado == 1 || ic.estado == 2), "idBono", "nombre", ingresoComunidadDet.bono);
            ViewBag.ingresoComunidad = new SelectList(db.IngresoComunidad, "idIngresoComunidad", "idIngresoComunidad", ingresoComunidadDet.ingresoComunidad);
            return View(ingresoComunidadDet);
        }

        // POST: IngresoComunidadDets/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idIngresoComunidadDet,ingresoComunidad,bono,denominacion,cantidad,subTotalBono")] IngresoComunidadDet ingresoComunidadDet)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ingresoComunidadDet).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.bono = new SelectList(db.ControlBono.Where(ic => ic.estado == 1 || ic.estado == 2), "idBono", "nombre", ingresoComunidadDet.bono);
            ViewBag.ingresoComunidad = new SelectList(db.IngresoComunidad, "idIngresoComunidad", "idIngresoComunidad", ingresoComunidadDet.ingresoComunidad);
            return View(ingresoComunidadDet);
        }

        // GET: IngresoComunidadDets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            vw_ingresocomunidaddet ingresoComunidadDet = db.vw_ingresocomunidaddet.Find(id);
            if (ingresoComunidadDet == null)
            {
                return HttpNotFound();
            }
            return View(ingresoComunidadDet);
        }

        // POST: IngresoComunidadDets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            IngresoComunidadDet ingresoComunidadDet = db.IngresoComunidadDet.Find(id);
            db.IngresoComunidadDet.Remove(ingresoComunidadDet);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult VerReporteIngresoComunidadDet(string tipo, string buscar = "")
        {
            LocalReport rpt = new LocalReport();
            string mt, enc, f;
            string[] s;
            Warning[] w;

            string ruta = Path.Combine(Server.MapPath("~/Reportes"), "RIngresoComunidadDet.rdlc");
            string deviceInfo = @"<DeviceInfo>
                      <MarginTop>0cm</MarginTop>
                      <MarginLeft>0cm</MarginLeft>
                      <MarginRight>0cm</MarginRight>
                      <MarginBottom>0cm</MarginBottom>
                        <EmbedFonts>None</EmbedFonts>
                    </DeviceInfo>";

            rpt.ReportPath = ruta;

            DBKermesseElysiumEntities modelo = new DBKermesseElysiumEntities();

            List<vw_ingresocomunidaddet> lista = new List<vw_ingresocomunidaddet>();
            var ingcomunidad = from ic in db.vw_ingresocomunidaddet select ic;

            if (!string.IsNullOrEmpty(buscar))
            {
                ingcomunidad = ingcomunidad.Where(ic => ic.ingresoComunidad.Contains(buscar) || ic.bono.Contains(buscar) || ic.denominacion.Contains(buscar) || ic.bono.Contains(buscar));
            }

            lista = ingcomunidad.ToList();

            ReportDataSource rds = new ReportDataSource("DSIngresoComunidadDet", lista);
            rpt.DataSources.Add(rds);

            var b = rpt.Render(tipo, deviceInfo, out mt, out enc, out f, out s, out w);

            return File(b, mt);
        }

        public ActionResult VerReporteIngresoComunidadDetIndiv(int id)
        {
            LocalReport rpt = new LocalReport();
            string mt, enc, f;
            string[] s;
            Warning[] w;

            string ruta = Path.Combine(Server.MapPath("~/Reportes"), "RIngresoComunidadDetIndiv.rdlc");
            string deviceInfo = @"<DeviceInfo>
                      <MarginTop>0cm</MarginTop>
                      <MarginLeft>0cm</MarginLeft>
                      <MarginRight>0cm</MarginRight>
                      <MarginBottom>0cm</MarginBottom>
                        <EmbedFonts>None</EmbedFonts>
                    </DeviceInfo>";

            rpt.ReportPath = ruta;

            DBKermesseElysiumEntities modelo = new DBKermesseElysiumEntities();

            var ingresocomunidad = from ic in db.vw_ingresocomunidaddet select ic;
            ingresocomunidad = ingresocomunidad.Where(ic => ic.idIngresoComunidadDet == id);

            ReportDataSource rds = new ReportDataSource("DSIngresoComunidad", ingresocomunidad.ToList());
            rpt.DataSources.Add(rds);

            var b = rpt.Render("PDF", deviceInfo, out mt, out enc, out f, out s, out w);

            return File(b, mt);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KermesseElysium/Views/IngresoComunidadDets/Create.cshtml
@model KermesseElysium.Models.IngresoComunidadDet

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Opción del rol</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li class="breadcrumb-item"> @Html.ActionLink("Ingreso de la comunidad", "Index", "IngresoComunidads")</li>
                    <li class="breadcrumb-item"> @Html.ActionLink("Detalle de ingresos", "Index", "IngresoComunidadDets")</li>
                    <li class="breadcrumb-item active">Añadir detalle de ingreso</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
        <div class="row mb-2">

        </div>
    </div><!-- /.container-fluid -->
</div>

<div class="card card-secondary">
    <div class="card-header">
        <h3 class="card-title">Añadir detalle de ingreso</h3>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="card-body">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.ingresoComunidad, "ingresoComunidad", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("ingresoComunidad", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ingresoComunidad, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.bono, "bono", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("bono", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.bono, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.denominacion, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.denominacion, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.denominacion, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.cantidad, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.cantidad, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.subTotalBono, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.subTotalBono, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.subTotalBono, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <input type="submit" value="Añadir" class="btn btn-secondary" />
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KermesseElysium/Views/IngresoComunidadDets/Delete.cshtml
@model KermesseElysium.Models.vw_ingresocomunidaddet

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Ingreso de la comunidad</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li class="breadcrumb-item"> @Html.ActionLink("Ingreso de la comunidad", "Index", "IngresoComunidads")</li>
                    <li class="breadcrumb-item"> @Html.ActionLink("Detalle de ingresos", "Index", "IngresoComunidadDets")</li>
                    <li class="breadcrumb-item active">Eliminar</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
        <div class="row mb-2">

        </div>
    </div><!-- /.container-fluid -->
</div>

<div class="card card-secondary">
    <div class="card-header">
        <h3 class="card-title">¿Estás seguro que deseas eliminar este detalle del ingreso?</h3>
    </div>
    <div class="card-body">
        <div class="info-box bg-light">
            <div class="info-box-content">
                @Html.LabelFor(model => model.ingresoComunidad, htmlAttributes: new { @class = "info-box-number mb-0" })
                <span class="info-box-text">@Html.DisplayFor(model => model.ingresoComunidad)</span>
            </div>
        </div>
        <div class="info-box bg-light">
            <div class="info-box-content">
                @Html.LabelFor(model => model.bono, htmlAttributes: new { @class = "info-box-number mb-0" })
                <span class="info-box-text">@Html.DisplayFor(model => model.bono)</span>
            </div>
        </div>
        <div class="info-box bg-light">
            <div class="info-box-content">
                @Html.LabelFor(model => model.denominacion, htmlAttributes: new { @class = "info-box-number mb-0" })
                <span class="info-box-text">@Html.DisplayFor(model => model.denominacion)</span>
            </div>
        </div>
        <div class="info-box bg-light">
            <div class="info-box-content">
                @Html.LabelFor(model => model.cantidad, htmlAttributes: new { @class = "info-box-number mb-0" })
                <span class="info-box-text">@Html.DisplayFor(model => model.cantidad)</span>
            </div>
        </div>
        <div class="info-box bg-light">
            <div class="info-box-content">
                @Html.LabelFor(model => model.subTotalBono, htmlAttributes: new { @class = "info-box-number mb-0" })
                <span class="info-box-text">@Html.DisplayFor(model => model.subTotalBono)</span>
            </div>
        </div>
    </div>
    <div class="card-footer">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Eliminar" class="btn btn-secondary" />
                <a class="btn btn-default" href="@Url.Action("Index", "IngresoComunidadDets")">Volver</a>
            </div>
        }
    </div>
</div>

KermesseElysium/Views/IngresoComunidadDets/Details.cshtml
@model KermesseElysium.Models.vw_ingresocomunidaddet

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Ingreso de la comunidad</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li class="breadcrumb-item"> @Html.ActionLink("Ingreso de la comunidad", "Index", "IngresoComunidads")</li>
                    <li class="breadcrumb-item"> @Html.ActionLink("Detalle de ingresos", "Index", "IngresoComunidadDets")</li>
                    <li class="breadcrumb-item active">Detalles</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
        <div class="row mb-2">

        </div>
    </div><!-- /.container-fluid -->
</div>

<div class="card card-secondary">
    <div class="card-header">
        <h3 class="card-title">Detalles del detalle del ingreso</h3>
    </div>
    <div class="card-body">
        <div class="info-box bg-light">
            <div class="info-box-content">
                @Html.LabelFor(model => model.ingresoComunidad, htmlAttributes: new { @class = "info-box-number mb-0" })
                <span class="info-box-text"> @Html.DisplayFor(model => model.ingresoComunidad)</span>
            </div>
        </div>
        <div class="info-box bg-light">
            <div class="info-box-content">
                @Html.LabelFor(model => model.bono, htmlAttributes: new { @class = "info-box-number mb-0" })
                <span class="info-box-text">@Html.DisplayFor(model => model.bono)</span>
            </div>
        </div>
        <div class="info-box bg-light">
            <div class="info-box-content">
                @Html.LabelFor(model => model.denominacion, htmlAttributes: new { @class = "info-box-number mb-0" })
                <span class="info-box-text">@Html.DisplayFor(model => model.denominacion)</span>
            </div>
        </div>
        <div class="info-box bg-light">
            <div class="info-box-content">
                @Html.LabelFor(model => model.cantidad, htmlAttributes: new { @class = "info-box-number mb-0" })
                <span class="info-box-text">@Html.DisplayFor(model => model.cantidad)</span>
            </div>
        </div>
        <div class="info-box bg-light">
            <div class="info-box-content">
                @Html.LabelFor(model => model.subTotalBono, htmlAttributes: new { @class = "info-box-number mb-0" })
                <span class="info-box-text">@Html.DisplayFor(model => model.subTotalBono)</span>
            </div>
        </div>
    </div>
    <div class="card-footer">
        <a class="btn btn-default" href="@Url.Action("Index", "IngresoComunidadDets")">Volver</a>
    </div>
</div>

KermesseElysium/Views/IngresoComunidadDets/Edit.cshtml
@model KermesseElysium.Models.IngresoComunidadDet

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Ingreso de la comunidad</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li class="breadcrumb-item"> @Html.ActionLink("Ingreso de la comunidad", "Index", "IngresoComunidads")</li>
                    <li class="breadcrumb-item"> @Html.ActionLink("Detalle de ingresos", "Index", "IngresoComunidadDets")</li>
                    <li class="breadcrumb-item active">Editar</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
        <div class="row mb-2">

        </div>
    </div><!-- /.container-fluid -->
</div>

<div class="card card-secondary">
    <div class="card-header">
        <h3 class="card-title">Editar el ingreso de la comunidad</h3>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="card-body">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.idIngresoComunidadDet)

                <div class="form-group">
                    @Html.LabelFor(model => model.ingresoComunidad, "ingresoComunidad", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("ingresoComunidad", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ingresoComunidad, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.bono, "bono", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("bono", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.bono, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.denominacion, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.denominacion, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.denominacion, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.cantidad, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.cantidad, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.subTotalBono, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.subTotalBono, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.subTotalBono, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Actualizar" class="btn btn-secondary" />
                    </div>
                </div>
            </div>
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KermesseElysium/Views/IngresoComunidadDets/Index.cshtml
@model IEnumerable<KermesseElysium.Models.vw_ingresocomunidaddet>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Ingreso de la comunidad</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li class="breadcrumb-item"> @Html.ActionLink("Ingreso de la comunidad", "Index", "IngresoComunidads")</li>
                    <li class="breadcrumb-item active">Detalles de los ingresos</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
        <div class="row mb-2">

        </div>
    </div><!-- /.container-fluid -->
</div>

<div class="card">
    <div class="card-header">
        <div style="text-align:right;">
            <button type="button" class="btn btn-secondary btn-sm" onclick="location.href='@Url.Action("Create", "IngresoComunidadDets")'">
                <i class="fas fa-plus"></i> Agregar nuevo detalle
            </button>
            <div class="btn-group">
                <button type="button" class="btn-sm btn-secondary dropdown-toggle dropdown-icon border border-secondary" data-toggle="dropdown">
                    Exportar
                </button>
                <div class="dropdown-menu" role="menu">
                    <a class="dropdown-item" href="@Url.Action("VerReporteIngresoComunidadDet", new { tipo = "PDF", buscar = Request.Form["buscar"] })">PDF</a>
                    <a class="dropdown-item" href="@Url.Action("VerReporteIngresoComunidadDet", new { tipo = "Word", buscar = Request.Form["buscar"] })">Word</a>
                    <a class="dropdown-item" href="@Url.Action("VerReporteIngresoComunidadDet", new { tipo = "Excel", buscar = Request.Form["buscar"] })">Excel</a>
                </div>
            </div>
        </div>
    </div>

    <div class="card-body">
        @using (Html.BeginForm("Index", "IngresoComunidadDets", FormMethod.Post))
        {
            <div style="text-align:right; float:right;">
                <div class"row">
                    <div class="input-group">
                        @Html.TextBox("buscar", "", new { @class = "form-control" })
                        <button type="submit" class="btn btn-dark">Buscar</button>
                    </div>
                </div>
            </div>
        }
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.ingresoComunidad)</th>
                    <th>@Html.DisplayNameFor(model => model.bono)</th>
                    <th>@Html.DisplayNameFor(model => model.denominacion)</th>
                    <th>@Html.DisplayNameFor(model => model.cantidad)</th>
                    <th>@Html.DisplayNameFor(model => model.subTotalBono)</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ingresoComunidad)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.bono)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.denominacion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.cantidad)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.subTotalBono)
                    </td>
                    <td>
                        <span style="cursor:pointer;" title="Ver detalles"><a href="@Url.Action("Details", "IngresoComunidadDets", new { id = item.idIngresoComunidadDet })" style="color:black;"><i class="fas fa-eye"></i></a></span>
                        <span style="cursor:pointer;" title="Editar"><a href="@Url.Action("Edit", "IngresoComunidadDets", new { id = item.idIngresoComunidadDet })" style="color:black;"><i class="fas fa-edit"></i></a></span>
                        <span style="cursor:pointer;" title="Eliminar"><a href="@Url.Action("Delete", "IngresoComunidadDets", new { id = item.idIngresoComunidadDet })" style="color:black;"><i class="fas fa-trash"></i></a></span>
                        <span style="cursor:pointer;" title="Exportar a PDF"><a href="@Url.Action("VerReporteIngresoComunidadDetIndiv", "IngresoComunidadDets", new { id = item.idIngresoComunidadDet })" style="color:black;"><i class="fas fa-file-export"></i></a></span>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>

</div>