KermesseElysium/Controllers/KermessesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KermesseElysium.Models;
using Microsoft.Reporting.WebForms;

namespace KermesseElysium.Controllers
{
    public class KermessesController : Controller
    {
        private DBKermesseElysiumEntities db = new DBKermesseElysiumEntities();

        // GET: Kermesses1
        public ActionResult Index(string buscar = "")
        {
            var kermesse = from g in db.Kermesse select g;

            kermesse = kermesse.Where(p => p.estado.Equals(2) || p.estado.Equals(1));


            if (!string.IsNullOrEmpty(buscar))
            {
                kermesse = kermesse.Where(g => g.nombre.Contains(buscar));
            }

            return View(kermesse.ToList());
        }
        // GET: Kermesses1/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kermesse kermesse = db.Kermesse.Find(id);
            if (kermesse == null)
            {
                return HttpNotFound();
            }
            return View(kermesse);
        }

        // GET: Kermesses1/Create
        public ActionResult Create()
        {
            ViewBag.parroquia = new SelectList(db.Parroquia, "idParroquia", "nombre");
            ViewBag.usuarioCreacion = new SelectList(db.Usuario, "idUsuario", "userName");
            ViewBag.usuarioModificacion = new SelectList(db.Usuario, "idUsuario", "userName");
            ViewBag.usuarioEliminacion = new SelectList(db.Usuario, "idUsuario", "userName");
            return View();
        }

        // POST: Kermesses1/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idKermesse,parroquia,nombre,fInicio,fFinal,descripcion,estado,usuarioCreacion,fechaCreacion,usuarioModificacion,fechaModificacion,usuarioEliminacion,fechaEliminacion")] Kermesse kermesse)
        {
            if (ModelState.IsValid)
            {
                String temp = Convert.ToString(Session["idUser"]);
                int idu = int.Parse(temp);
                kermesse.fechaCreacion =  DateTime.Today;
                kermesse.estado = 1;
                kermesse.usuarioCreacion = idu;
                db.Kermesse.Add(kermesse);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.parroquia = new SelectList(db.Parroquia, "idParroquia", "nombre", kermesse.parroquia);
            ViewBag.usuarioCreacion = new SelectList(db.Usuario, "idUsuario", "userName", kermesse.usuarioCreacion);
            ViewBag.usuarioModificacion = new SelectList(db.Usuario, "idUsuario", "userName", kermesse.usuarioModificacion);
            ViewBag.usuarioEliminacion = new SelectList(db.Usuario, "idUsuario", "userName", kermesse.usuarioEliminacion);
            return View(kermesse);
        }

        // GET: Kermesses1/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kermesse kermesse = db.Kermesse.Find(id);
            if (kermesse == null)
            {
                return HttpNotFound();
            }
            ViewBag.parroquia = new SelectList(db.Parroquia, "idParroquia", "nombre", kermesse.parroquia);
            ViewBag.usuarioCreacion = new SelectList(db.Usuario, "idUsuario", "userName", kermesse.usuarioCreacion);
            ViewBag.usuarioModificacion = new SelectList(db.Usuario, "idUsuario", "userName", kermesse.usuarioModificacion);
            ViewBag.usuarioEliminacion = new SelectList(db.Usuario, "idUsuario", "userName", kermesse.usuarioEliminacion);
            return View(kermesse);
        }

        // POST: Kermesses1/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idKermesse,parroquia,nombre,fInicio,fFinal,descripcion,estado,usuarioCreacion,fechaCreacion,usuarioModificacion,fechaModificacion,usuarioEliminacion,fechaEliminacion")] Kermesse kermesse)
        {
            if (ModelState.IsValid)
            {
                String temp = Convert.ToString(Session["idUser"]);
                int idu = int.Parse(temp);
                kermesse.fechaCreacion = DateTime.Today;
                kermesse.estado = 1;
                kermesse.usuarioCreacion = idu;
                db.Entry(kermesse).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.parroquia = new SelectList(db.Parroquia, "idParroquia", "nombre", kermesse.parroquia);
            ViewBag.usuarioCreacion = new SelectList(db.Usuario, "idUsuario", "userName", kermesse.usuarioCreacion);
            ViewBag.usuarioModificacion = new SelectList(db.Usuario, "idUsuario", "userName", kermesse.usuarioModificacion);
            ViewBag.usuarioEliminacion = new SelectList(db.Usuario, "idUsuario", "userName", kermesse.usuarioEliminacion);
            return View(kermesse);
        }

        // GET: Kermesses1/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kermesse kermesse = db.Kermesse.Find(id);
            if (kermesse == null)
            {
                return HttpNotFound();
            }
            return View(kermesse);
        }

        // POST: Kermesses1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Kermesse kermesse = db.Kermesse.Find(id);

            kermesse.estado = 3;

            db.Entry(kermesse).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult VerReporteResumen(string buscar = "")
        {

            LocalReport rpt = new LocalReport();
            string mt, enc, f;
            string[] s;
            Warning[] w;

            string ruta = Path.Combine(Server.MapPath("~/Reportes"), "RReporteResumen.rdlc");
            string deviceInfo = @"<DeviceInfo>
                      <MarginTop>0cm</MarginTop>
                      <MarginLeft>0cm</MarginLeft>
                      <MarginRight>0cm</MarginRight>
                      <MarginBottom>0cm</MarginBottom>
                        <EmbedFonts>None</EmbedFonts>
                    </DeviceInfo>";

            rpt.ReportPath = ruta;

            var ingresoComunidad = from ic in db.vw_resumenkermesse select ic;

            if (!string.IsNullOrEmpty(buscar))
            {
                ingresoComunidad = ingresoComunidad.Where(c => c.kermesse.Contains(buscar));
            }

            List<vw_resumenkermesse> listaIngCom = new List<vw_resumenkermesse>();
            listaIngCom = ingresoComunidad.ToList();

            ReportDataSource rds = new ReportDataSource("DsResumenKermesse", listaIngCom);
            rpt.DataSources.Add(rds);

            byte[] b = rpt.Render("PDF", deviceInfo, out mt, out enc, out f, out s, out w);

            return File(b, mt);

        }
        public ActionResult VerReporteKermesses(string tipo, string buscar = "")
        {

            LocalReport rpt = new LocalReport();
            string mt, enc, f;
            string[] s;
            Warning[] w;

            string ruta = Path.Combine(Server.MapPath("~/Reportes"), "RKermesse.rdlc");

            rpt.ReportPath = ruta;

            DBKermesseElysiumEntities modelo = new DBKermesseElysiumEntities();

            var Lista = from m in db.vw_kermesse select m;

            if (!string.IsNullOrEmpty(buscar))
            {
                Lista = Lista.Where(m => m.nombre.Contains(buscar));
            }

            List<vw_kermesse> listap = new List<vw_kermesse>();
            listap = Lista.ToList();

            ReportDataSource rds = new ReportDataSource("DSKermesse", listap);
            rpt.DataSources.Add(rds);

            var b = rpt.Render(tipo, null, out mt, out enc, out f, out s, out w);

            return File(b, mt);
        }

        public ActionResult VerReporteKermessesIndiv(int id)
        {
            LocalReport rpt = new LocalReport();
            string mt, enc, f;
            string[] s;
            Warning[] w;

            string ruta = Path.Combine(Server.MapPath("~/Reportes"), "RKermesseIndiv.rdlc");
            string deviceInfo = @"<DeviceInfo>
                      <MarginTop>0cm</MarginTop>
                      <MarginLeft>0cm</MarginLeft>
                      <MarginRight>0cm</MarginRight>
                      <MarginBottom>0cm</MarginBottom>
                        <EmbedFonts>None</EmbedFonts>
                    </DeviceInfo>";

            rpt.ReportPath = ruta;


            var Lista = from m in db.vw_kermesse select m;


            Lista = Lista.Where(m => m.idKermesse == id);

            ReportDataSource rds = new ReportDataSource("DSKermesseIndiv", Lista.ToList());
            rpt.DataSources.Add(rds);

            var b = rpt.Render("PDF", deviceInfo, out mt, out enc, out f, out s, out w);

            return File(b, mt);
        }

KermesseElysium/Views/Kermesses/Create.cshtml
@model KermesseElysium.Models.Kermesse

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Kermesse</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li class="breadcrumb-item"> @Html.ActionLink("Kermesse", "Index", "Kermesses")</li>
                    <li class="breadcrumb-item active">Crear</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
        <div class="row mb-2">

        </div>
    </div><!-- /.container-fluid -->
</div>

<div class="card card-secondary">
    <div class="card-header">
        <h3 class="card-title">Registrar Kermese</h3>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="card-body">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.parroquia, "parroquia", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("parroquia", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.parroquia, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.fInicio, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.fInicio, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                        @Html.ValidationMessageFor(model => model.fInicio, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.fFinal, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.fFinal, new { htmlAttributes = new { @class = "form-control", type="date" } })
                        @Html.ValidationMessageFor(model => model.fFinal, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                    </div>
                </div>
                 

            </div>
        </div>
        <div class="card-footer">
            <input type="submit" value="Crear" class="btn btn-secondary" />
        </div>
    }
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KermesseElysium/Views/Kermesses/Delete.cshtml
@model KermesseElysium.Models.Kermesse

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Kermesse</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.nombre)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.nombre)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.fInicio)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.fInicio)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.fFinal)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.fFinal)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.descripcion)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.descripcion)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.estado)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.estado)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.fechaCreacion)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.fechaCreacion)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.fechaModificacion)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.fechaModificacion)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.fechaEliminacion)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.fechaEliminacion)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Parroquia1.nombre)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Parroquia1.nombre)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Usuario.userName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Usuario.userName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Usuario1.userName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Usuario1.userName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Usuario2.userName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Usuario2.userName)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

KermesseElysium/Views/Kermesses/Details.cshtml
@model KermesseElysium.Models.Kermesse

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Kermesse</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li class="breadcrumb-item"> @Html.ActionLink("Kermesse", "Index", "Kermesses")</li>
                    <li class="breadcrumb-item active">Detalles</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
        <div class="row mb-2">

        </div>
    </div><!-- /.container-fluid -->
</div>

<div class="card card-secondary">
    <div class="card-header">
        <h3 class="card-title">Detalles de la Kermesse</h3>
    </div>
    <div class="card-body">
        <div class="info-box bg-light">
            <div class="info-box-content">
                @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "info-box-number mb-0" })
                <span class="info-box-text">@Html.DisplayFor(model => model.nombre)</span>
            </div>
        </div>
        <div class="info-box bg-light">
            <div class="info-box-content">
                @Html.LabelFor(model => model.fInicio, htmlAttributes: new { @class = "info-box-number mb-0" })
                <span class="info-box-text">@Html.DisplayFor(model => model.fInicio)</span>
            </div>
        </div>
        <div class="info-box bg-light">
            <div class="info-box-content">
                @Html.LabelFor(model => model.fFinal, htmlAttributes: new { @class = "info-box-number mb-0" })
                <span class="info-box-text">@Html.DisplayFor(model => model.fFinal)</span>
            </div>
        </div>
        <div class="info-box bg-light">
            <div class="info-box-content">
                @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "info-box-number mb-0" })
                <span class="info-box-text">@Html.DisplayFor(model => model.descripcion)</span>
            </div>
        </div>
        <div class="info-box bg-light">
            <div class="info-box-content">
                @Html.LabelFor(model => model.fechaCreacion, htmlAttributes: new { @class = "info-box-number mb-0" })
                <span class="info-box-text">@Html.DisplayFor(model => model.fechaCreacion)</span>
            </div>
        </div>

    </div>
    <div class="card-footer">
        <a class="btn btn-default" href="@Url.Action("Index", "Kermesses")">Volver</a>
    </div>
</div>

KermesseElysium/Views/Kermesses/Edit.cshtml
@model KermesseElysium.Models.Kermesse
    @{ 
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Kermesse</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li class="breadcrumb-item"> @Html.ActionLink("Kermesse", "Index", "Kermesses")</li>
                    <li class="breadcrumb-item active">Editar</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
        <div class="row mb-2">

        </div>
    </div><!-- /.container-fluid -->
</div>

<div class="card card-secondary">
    <div class="card-header">
        <h3 class="card-title">Editar Kermesse</h3>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="card-body">
            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.idKermesse)

                <div class="form-group">
                    @Html.LabelFor(model => model.parroquia, "parroquia", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("parroquia", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.parroquia, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.fInicio, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.fInicio, new { htmlAttributes = new { @class = "form-control" , type="date"} })
                        @Html.ValidationMessageFor(model => model.fInicio, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.fFinal, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.fFinal, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                        @Html.ValidationMessageFor(model => model.fFinal, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                    </div>
                </div>
 
         

                

              
            </div>
            <div class="card-footer">
                <input type="submit" value="Actualizar" class="btn btn-secondary" />
            </div>
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KermesseElysium/Views/Kermesses/Index.cshtml
@model IEnumerable<KermesseElysium.Models.Kermesse>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Kermesses</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li class="breadcrumb-item active">Kermesses</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
        <div class="row mb-2">

        </div>
    </div><!-- /.container-fluid -->
</div>

<div class="card">
    <div class="card-header">
        <div style="text-align:right;">
            <button type="button" class="btn btn-secondary btn-sm" onclick="location.href='@Url.Action("Create", "Kermesses")'">
                <i class="fas fa-plus"></i> Agregar nueva kermesses
            </button>
            <div class="btn-group">
                <button type="button" class="btn-sm btn-secondary dropdown-toggle dropdown-icon border border-secondary" data-toggle="dropdown">
                    Exportar
                </button>
                <div class="dropdown-menu" role="menu">
                    <a class="dropdown-item" href="@Url.Action("VerReporteKermesses", new { tipo = "PDF", buscar = Request.Form["buscar"] })">PDF</a>
                    <a class="dropdown-item" href="@Url.Action("VerReporteKermesses", new { tipo = "Word", buscar = Request.Form["buscar"] })">Word</a>
                    <a class="dropdown-item" href="@Url.Action("VerReporteKermesses", new { tipo = "Excel", buscar = Request.Form["buscar"] })">Excel</a>
                </div>
            </div>
            <button type="button" class="btn btn-secondary btn-sm" onclick="location.href='@Url.Action("VerReporteResumen", new { buscar = Request.Form["buscar"] })'">
                <i class="fas fa-file-export"></i>Resumen
            </button>
        </div>
    </div>

    <div class="card-body">
        @using (Html.BeginForm("Index", "Kermesses", FormMethod.Post))
        {
            <div style="text-align:right; float:right;">
                <div class"row">
                    <div class="input-group">
                        @Html.TextBox("buscar", "", new { @class = "form-control" })
                        <button type="submit" class="btn btn-dark">Buscar</button>
                    </div>
                </div>
            </div>
        }
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>
                    @Html.DisplayNameFor(model => model.nombre)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.fInicio)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.fFinal)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.descripcion)
                    </th>
                     
                    
                    <th>
                        @Html.DisplayNameFor(model => model.Parroquia1.nombre)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Usuario.userName)
                    </th>
               
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.fInicio)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.fFinal)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.descripcion)
                    </td>
                    
                   
                    <td>
                        @Html.DisplayFor(modelItem => item.Parroquia1.nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Usuario.userName)
                    </td>
                    

                    <td>
                        <span style="cursor:pointer;" title="Ver detalles"><a href="@Url.Action("Details", "Kermesses", new { id = item.idKermesse })" style="color:black;"><i class="fas fa-eye"></i></a></span>
                        <span style="cursor:pointer;" title="Editar"><a href="@Url.Action("Edit", "Kermesses", new { id = item.idKermesse })" style="color:black;"><i class="fas fa-edit"></i></a></span>
                        <span style="cursor:pointer;" title="Eliminar"><a href="@Url.Action("Delete", "Kermesses", new { id = item.idKermesse })" style="color:black;"><i class="fas fa-trash"></i></a></span>
                        <span style="cursor:pointer;" title="Exportar a PDF"><a href="@Url.Action("VerReporteKermessesIndiv", "Kermesses", new { id = item.idKermesse })" style="color:black;"><i class="fas fa-file-export"></i></a></span>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>

</div>